blank_issues_enabled: true
contact_links:
  - name: Code of Conduct
    url: https://github.com/djryanj/k8s-rbactory-frontend/blob/main/CODE_OF_CONDUCT.md
    about: Please review our Code of Conduct before participating